import { SymbolLayer } from "mapbox-gl";

export const getImuPoiStyle = (route: string): SymbolLayer => {
  return {
    id: "imu-poi-opacity",
    type: "symbol",
    source: "composite",
    "source-layer": "imu_poi",
    layout: {
      "text-field": ["concat", ["to-string", ["get", "distance_at"]], " km"],
      "text-font": ["Open Sans SemiBold", "Arial Unicode MS Regular"],
      "icon-image": [
        "match",
        ["get", "type"],
        ["ws"],
        "water-drop-5881",
        ["as"],
        "first-aid-kit-3949",
        ["cp"],
        "red-location-placeholder-and-check-mark-15943",
        "",
      ],
      "icon-size": [
        "match",
        ["get", "type"],
        ["ws"],
        0.1,
        ["as"],
        0.12,
        ["cp"],
        0.13,
        1,
      ],
      "text-anchor": "right",
      "text-offset": [-1.2, 0],
      "icon-allow-overlap": true,
      "icon-ignore-placement": true,
      "text-ignore-placement": true,
      "text-allow-overlap": true,
    },
    paint: {
      "text-color": "hsl(0, 0%, 100%)",
      "text-halo-color": "hsl(0, 0%, 0%)",
      "text-halo-width": 2,
      "text-halo-blur": 1,
      "text-opacity": ["match", ["get", "route-code"], [`${route}`], 1, 0],
      "icon-opacity": ["match", ["get", "route-code"], [`${route}`], 1, 0],
    },
  };
};

export const imuPoiStyle: SymbolLayer = {
  id: "imu-poi-opacity",
  type: "symbol",
  source: "composite",
  "source-layer": "imu_poi",
  layout: {
    "text-field": ["concat", ["to-string", ["get", "distance_at"]], " km"],
    "text-font": ["Open Sans SemiBold", "Arial Unicode MS Regular"],
    "icon-image": [
      "match",
      ["get", "type"],
      ["ws"],
      "water-drop-5881",
      ["as"],
      "first-aid-kit-3949",
      ["cp"],
      "red-location-placeholder-and-check-mark-15943",
      "",
    ],
    "icon-size": [
      "match",
      ["get", "type"],
      ["ws"],
      0.1,
      ["as"],
      0.12,
      ["cp"],
      0.13,
      1,
    ],
    "text-anchor": "right",
    "text-offset": [-1.2, 0],
    "icon-allow-overlap": true,
    "icon-ignore-placement": true,
    "text-ignore-placement": true,
    "text-allow-overlap": true,
  },
  paint: {
    "text-color": "hsl(0, 0%, 100%)",
    "text-halo-color": "hsl(0, 0%, 0%)",
    "text-halo-width": 2,
    "text-halo-blur": 1,
    "text-opacity": 0,
    "icon-opacity": 0,
  },
};
